lsi: false
safe: true
source: /Users/rogerpierce/Documents/GitHub/octopusobserver.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
